spring:
  application:
    name: gestor-tareas
  datasource:
    url: jdbc:mysql://localhost:3306/gertoraquaris
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000